version: '3.4'

networks:
  dbconfigurator:

services:
  db:
    container_name: app-db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "8002:1433"
    environment:
      SA_PASSWORD: "YourSAPassword1"
      ACCEPT_EULA: "Y"
    networks: 
       - dbconfigurator
    volumes:
       - dbdata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  dbconfigurator.api:
    container_name: dbconfiguratorapi
    image: ${DOCKER_REGISTRY-}dbconfiguratorapi
    build:
      context: .
      dockerfile: DbConfigurator.Api/Dockerfile
    ports:
        - 8001:80
        - 8443:443
    depends_on: 
        - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      Authentication_Issuer: "https://localhost:8443"
      Authentication_Audience: "dbconfiguratorapi"
      Authentication_SecretForKey: "thisisthesecretforgeneratingakey(mustbeatleast64bitlong)thisisthesecretforgeneratingakey(mustbeatleast64bitlong)"
    networks: 
       - dbconfigurator

volumes:
  dbdata: